spring:
  datasource:
    url: jdbc:mysql://localhost:3306/languageexcercise
    username: root
    password:

  jpa:
    database: mysql
    #show-sql: true
    hibernate:
      ddl-auto: update
    #properties:
    #  hibernate:
    #    format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  #E-MAILS
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false


db:
  admin:
    user:
      reset: false



